- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: true

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: true

- name: Pull frontend Docker image
  community.docker.docker_image:
    name: "{{ docker_image }}"
    source: pull

- name: Run or update frontend container
  community.docker.docker_container:
    name: "{{ docker_container_name }}"
    image: "{{ docker_image }}"
    state: started
    restart_policy: always
    ports:
      - "{{ host_port }}:{{ container_port }}"
    env:
      BACKEND_IP: "{{ backend_ip }}"
    recreate: yes 

- name: Stop frontend container
  community.docker.docker_container:
    name: "{{ docker_container_name }}"
    state: stopped
    timeout: 10

- name: Start frontend container
  community.docker.docker_container:
    name: "{{ docker_container_name }}"
    state: started