sonar.projectKey=class_schedule
sonar.modules=backend,frontend

backend.sonar.projectBaseDir=backend/backend
backend.sonar.sources=src
backend.sonar.java.binaries=build/classes/java/main

frontend.sonar.projectBaseDir=frontend/frontend
frontend.sonar.sources=src
