- name: Check if Datadog agent is installed
  command: which datadog-agent
  register: datadog_agent_check
  ignore_errors: yes
  changed_when: false

- name: Show message if Datadog agent is not installed
  debug:
    msg: "Datadog agent NOT installed"
  when: datadog_agent_check.rc != 0

- name: Check Datadog agent status
  command: datadog-agent status
  register: datadog_agent_status
  failed_when: datadog_agent_status.rc != 0
  changed_when: false
  when: datadog_agent_check.rc == 0

- name: Show Datadog agent status output
  debug:
    var: datadog_agent_status.stdout
  when: datadog_agent_check.rc == 0
