- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    bastion_ip: "{{ lookup('file', '../../terraform/tf_outputs.json') | from_json | json_query('bastion_external_ip.value') }}"
    ssh_user: "{{ lookup('file', '../../terraform/tf_outputs.json') | from_json | json_query('ssh_user.value') }}"
    bastion_key: "/var/lib/jenkins/.ssh/id_rsa_bastion"
    over_bastion_key: "/var/lib/jenkins/.ssh/id_rsa_over_bastion"

  tasks:
    - name: Create SSH config from template
      template:
        src: templates/ssh_config.j2
        dest: /var/lib/jenkins/.ssh/config
        mode: '0600'

    - name: Test connectivity to all hosts
      command: >
        ansible all
        -i ../inventory.ini
        -m ping
      register: ping_result
      environment:
        ANSIBLE_CONFIG: "./ansible.cfg"
      changed_when: false

    - name: Show ping results
      debug:
        var: ping_result.stdout_lines
