- hosts: frontend
  become: true
  roles:
    - role: frontend
      tags: frontend

- hosts: reverse_proxy
  become: true
  roles:
    - role: reverse_proxy
      tags: reverse_proxy

- hosts: database
  become: true
  roles:
    - role: database
      tags: database

- hosts: backend
  become: true
  vars:
    database_ip: 10.0.2.5
    database_name: "class_schedule"
  roles:
    - role: backend
      tags: backend

- hosts: all
  become: true
  roles:
    - node_exporter

- hosts: monitoring
  become: true
  roles:
    - role: monitoring
      tags: monitoring

- hosts: frontend, reverse_proxy, backend, database
  become: true
  vars:
    datadog_api_key: "{{ datadog_api_key }}"
    datadog_site: "datadoghq.com"
  environment:
    DEBIAN_FRONTEND: noninteractive
  tasks:
    - name: Ensure datadog.yaml with API key exists
      copy:
        dest: /etc/datadog-agent/datadog.yaml
        content: |
          api_key: "{{ datadog_api_key }}"
          logs_enabled: true
          apm_config:
            enabled: true
      notify: Restart datadog-agent
      tags: datadog

    - name: Start and enable Datadog Agent
      systemd:
        name: datadog-agent
        state: started
        enabled: true
      tags: datadog

    - name: Import the Datadog Agent role from the Datadog collection
      import_role:
        name: datadog.dd.agent
      tags: datadog

  handlers:
    - name: Restart datadog-agent
      become: true
      systemd:
        name: datadog-agent
        state: restarted