name: App build & Upload to GCS

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  build-war:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11' 

      - name: Grant permission to gradle
        run: chmod +x gradlew
        working-directory: backend/backend

      - name: Build WAR
        run: ./gradle clean war
        working-directory: backend/backend

      - name: Rename WAR file to ROOT.war
        run: mv build/libs/class_schedule.war build/libs/ROOT.war
        working-directory: backend/backend

      - name: Decode GCP credentials
        run: echo "${{ secrets.GCP_CREDENTIALS_BASE64 }}" | base64 -d > $HOME/gcp-creds.json

      - name: Install gcloud CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y google-cloud-cli

      - name: Authenticate with GCP
        run: gcloud auth activate-service-account --key-file=$HOME/gcp-creds.json

      - name: Upload WAR to Backend GCS bucket
        run: gsutil cp backend/backend/build/libs/ROOT.war gs://backend_artifacts_class_schedule/ROOT.war

  build-frontend:
    runs-on: ubuntu-latest
    needs: build-war

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 14.21.3
        uses: actions/setup-node@v3
        with:
          node-version: 14.21.3

      - name: Install dependencies and build frontend
        run: |
          cd frontend/frontend
          npm ci
          npm run build
        shell: bash

      - name: Archive frontend build with node_modules
        run: |
          cd frontend/frontend
          tar czf ../../frontend.tar.gz ./build ./node_modules

      - name: Decode GCP credentials
        run: echo "${{ secrets.GCP_CREDENTIALS_BASE64 }}" | base64 -d > $HOME/gcp-creds.json

      - name: Install gcloud CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y google-cloud-cli

      - name: Authenticate with GCP
        run: gcloud auth activate-service-account --key-file=$HOME/gcp-creds.json

      - name: Upload frontend archive to Frontend GCS bucket
        run: gsutil cp frontend.tar.gz gs://frontend_artifacts_class_schedule/frontend.tar.gz